[KUBE-145] Upgrade the preflight binary version to 1.19.1 (#1309)
# Summary

The [preflight images
task](https://spruce.corp.mongodb.com/version/mongodb_kubernetes_1.9.0_6a4411a2cb95810007f0c691/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
during the release of MCK 1.9.0 failed with below error

```
Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: \'github.com/redhat-openshift-ecosystem/openshift-preflight\' version \'1.16.0\' is not supported. Supported versions are: [\'1.19.0\', \'1.19.1\']", "status": 400, "trace_id": "0x8caf7bb97786953113f8986193361024"}\n2026/06/30 19:11:27
```

as we can see version 1.16.0 of preflight binary is not supported
anymore. This PR updates the binary version to 1.19.0.

## Proof of Work


[Tests](https://spruce.corp.mongodb.com/version/6a441ef00a439c0007a67e25/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
passed after the version bump.

## Checklist

- [x] Have you linked a jira ticket and/or is the ticket in the title?
- [x] Have you checked whether your jira ticket required DOCSP changes?
- [x] Have you added changelog file?
    - use `skip-changelog` label if not needed
- refer to [Changelog files and Release
Notes](https://github.com/mongodb/mongodb-kubernetes/blob/master/CONTRIBUTING.md#changelog-files-and-release-notes)
section in CONTRIBUTING.md for more details

---