Bump preflight binary to 1.11.1 + fix silenced error (#4041)
# Summary

Bumps preflight version to `1.11.1`. Previous version is not supported
anymore and
[build](https://spruce.mongodb.com/task/ops_manager_kubernetes_preflight_images_preflight_images_678f0db1e687200007b0ceb7_25_01_21_03_00_01/logs?execution=0)
_failed_:
```
Error: could not submit to pyxis: could not create test results: status code: 400: body: {"type": "about:blank", "title": "Bad Request", "detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.10.2' is not supported. Supported versions are: ['1.11.0', '1.11.1']", "status": 400, "trace_id": "0x50e3ae640a3d278175141e22520f3382"}
```

The error did not show up in evergreen task, because `subprocess.run()`
was specified without `check=True` argument.

## Documentation changes

* [ ] Add an entry to [release notes](.../RELEASE_NOTES.md).
* [ ] When needed, make sure you create a new [DOCSP
ticket](https://jira.mongodb.org/projects/DOCSP) that documents your
change.

## Changes to CRDs

* [ ] Add `slaskawi`(Sebastian) and `@giohan` (George) as reviewers.
* [ ] Make sure any changes are reflected on `/public/samples`
directory.