Fix release notes preview for non PRs (#592)
# Summary

Currently for master commits the Release Notes preview is failing:
```
Run cat release_notes_preview.md >> $GITHUB_STEP_SUMMARY
cat: release_notes_preview.md: No such file or directory
Error: Process completed with exit code 1.
```

## Proof of Work

Passing
https://github.com/mongodb/mongodb-kubernetes/actions/runs/19334673064/job/55306298991?pr=592

## Checklist

- [ ] Have you linked a jira ticket and/or is the ticket in the title?
- [ ] Have you checked whether your jira ticket required DOCSP changes?
- [x] Have you added changelog file?
    - use `skip-changelog` label if not needed
- refer to [Changelog files and Release
Notes](https://github.com/mongodb/mongodb-kubernetes/blob/master/CONTRIBUTING.md#changelog-files-and-release-notes)
section in CONTRIBUTING.md for more details