fix logger and controller-runtime logger (#4104)
# Summary

- refactors log creation and handling
  - better error handling
  - easier way to add dedicated loggers (e.g. telemetry)
- fixes edge-cases when logger is nil
- set controller-runtime logger to be the same as our operator logger.
Without we are not logging controller-runtime at all, which can cause
the following error on startup
```
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 605 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
```

## Proof of Work
- example other users with the same problem:
https://github.com/rook/rook/issues/12434 and
https://github.com/erda-project/erda/pull/6453
- example log from evg:
REDACTED
- example log
```
{"GVK": "mongodb.com/v1, Kind=MongoDB"}
2025-02-14T14:54:14.557Z	INFO	controller-runtime.builder	builder/webhook.go:193	Registering a validating webhook	{"GVK": "mongodb.com/v1, Kind=MongoDB", "path": "/validate-mongodb-com-v1-mongodb"}
2025-02-14T14:54:14.557Z	INFO	controller-runtime.webhook	webhook/server.go:183	Registering webhook	{"path": "/validate-mongodb-com-v1-mongodb"}
2025-02-14T14:54:14.557Z	INFO	operator/mongodbopsmanager_controller.go:951	Registered controller opsmanager-controller
2025-02-14T14:54:14.557Z	INFO	controller-runtime.builder	builder/webhook.go:177	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "mongodb.com/v1, Kind=MongoDBOpsManager"}
2025-02-14T14:54:14.557Z	INFO	controller-runtime.builder	builder/webhook.go:193	Registering a validating webhook	{"GVK": "mongodb.com/v1, Kind=MongoDBOpsManager", "path": "/validate-mongodb-com-v1-mongodbopsmanager"}
2025-02-14T14:54:14.557Z	INFO	controller-runtime.webhook	webhook/server.go:183	Registering webhook	{"path": "/validate-mongodb-com-v1-mongodbopsmanager"}
2025-02-14T14:54:14.557Z	INFO	operator/mongodbuser_controller.go:299	Registered controller mongodbuser-controller
2025-02-14T14:54:14.557Z	INFO	ops-manager-kubernetes/main.go:204	Registered CRD: mongodb
2025-02-14T14:54:14.557Z	INFO	ops-manager-kubernetes/main.go:204	Registered CRD: opsmanagers
2025-02-14T14:54:14.557Z	INFO	ops-manager-kubernetes/main.go:204	Registered CRD: mongodbusers
2025-02-14T14:54:14.557Z	INFO	ops-manager-kubernetes/main.go:207	Starting the Cmd.
2025-02-14T14:54:14.558Z	INFO	controller-runtime.metrics	server/server.go:208	Starting metrics server
2025-02-14T14:54:14.558Z	INFO	controller-runtime.webhook	webhook/server.go:191	Starting webhook server
2025-02-14T14:54:14.558Z	INFO	controller-runtime.metrics	server/server.go:247	Serving metrics server	{"bindAddress": ":8080", "secure": false}
2025-02-14T14:54:14.558Z	INFO	controller-runtime.certwatcher	certwatcher/certwatcher.go:211	Updated current TLS certificate
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbshardedcluster-controller", "source": "kind source: *mdb.MongoDB"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbshardedcluster-controller", "source": "channel source: 0xc000322c40"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbreplicaset-controller", "source": "kind source: *mdb.MongoDB"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbreplicaset-controller", "source": "channel source: 0xc000322bd0"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbreplicaset-controller", "source": "kind source: *v1.StatefulSet"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbuser-controller", "source": "kind source: *v1.ConfigMap"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbreplicaset-controller", "source": "kind source: *v1.ConfigMap"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbreplicaset-controller", "source": "kind source: *v1.Secret"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:181	Starting Controller	{"controller": "mongodbreplicaset-controller"}
2025-02-14T14:54:14.558Z	INFO	controller-runtime.webhook	webhook/server.go:242	Serving webhook server	{"host": "", "port": 1993}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbstandalone-controller", "source": "kind source: *mdb.MongoDB"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbshardedcluster-controller", "source": "kind source: *v1.ConfigMap"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbshardedcluster-controller", "source": "kind source: *v1.Secret"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:181	Starting Controller	{"controller": "mongodbshardedcluster-controller"}
2025-02-14T14:54:14.558Z	INFO	controller-runtime.certwatcher	certwatcher/certwatcher.go:133	Starting certificate poll+watcher	{"interval": "10s"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbuser-controller", "source": "kind source: *v1.Secret"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbuser-controller", "source": "kind source: *user.MongoDBUser"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbstandalone-controller", "source": "channel source: 0xc000322b60"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:181	Starting Controller	{"controller": "mongodbuser-controller"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbstandalone-controller", "source": "kind source: *v1.ConfigMap"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "mongodbstandalone-controller", "source": "kind source: *v1.Secret"}
2025-02-14T14:54:14.558Z	INFO	controller/controller.go:181	Starting Controller	{"controller": "mongodbstandalone-controller"}
2025-02-14T14:54:14.559Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "opsmanager-controller", "source": "kind source: *om.MongoDBOpsManager"}
2025-02-14T14:54:14.559Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "opsmanager-controller", "source": "kind source: *v1.Secret"}
2025-02-14T14:54:14.559Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "opsmanager-controller", "source": "kind source: *v1.Secret"}
2025-02-14T14:54:14.559Z	INFO	controller/controller.go:173	Starting EventSource	{"controller": "opsmanager-controller", "source": "kind source: *mdb.MongoDB"}
2025-02-14T14:54:14.559Z	INFO	controller/controller.go:181	Starting Controller	{"controller": "opsmanager-controller"}
2025-02-14T14:54:15.359Z	INFO	controller/controller.go:215	Starting workers	{"controller": "mongodbshardedcluster-controller", "worker count": 10}
2025-02-14T14:54:15.410Z	INFO	controller/controller.go:215	Starting workers	{"controller": "mongodbreplicaset-controller", "worker count": 10}
2025-02-14T14:54:15.460Z	INFO	controller/controller.go:215	Starting workers	{"controller": "mongodbstandalone-controller", "worker count": 10}
2025-02-14T14:54:15.610Z	INFO	controller/controller.go:215	Starting workers	{"controller": "mongodbuser-controller", "worker count": 10}
2025-02-14T14:54:15.660Z	INFO	controller/controller.go:215	Starting workers	{"controller": "opsmanager-controller", "worker count": 10}
2025-02-14T14:54:16.471Z	ERROR	admission	admission/http.go:72	bad request	{"webhookGroup": "mongodb.com", "webhookKind": "MongoDB", "error": "request body is empty"}
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.7/pkg/webhook/admission/http.go:72
sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics.InstrumentedHook.InstrumentHandlerInFlight.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/promhttp/instrument_server.go:60
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
	/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/promhttp/instrument_server.go:147
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
	/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/promhttp/instrument_server.go:109
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2220
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2747
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
```